-- +goose Up
-- Allocations aggregate table.
--
-- ID strategy: UUIDv7, generated by the APPLICATION (not the database) so an
-- aggregate has its identity before any I/O and inserts stay idempotent
-- under retries. v7 is time-ordered: new rows append to the right edge of
-- the PK index (no random-UUID page splits) and the id is a stable
-- tie-breaker for (created_at, id) cursor pagination.
--
-- All timestamps are timestamptz stored in UTC.
CREATE TABLE allocations (
    id          uuid PRIMARY KEY,
    tenant_id   text        NOT NULL CHECK (length(tenant_id) BETWEEN 1 AND 128),
    request_id  text        NOT NULL CHECK (length(request_id) BETWEEN 1 AND 128),
    resource_id text        NOT NULL CHECK (length(resource_id) BETWEEN 1 AND 128),
    status      text        NOT NULL CHECK (status IN ('PENDING','ALLOCATED','RELEASED','COMPLETED','EXPIRED','FAILED')),
    priority    integer     NOT NULL DEFAULT 0 CHECK (priority BETWEEN 0 AND 1000),
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL,
    expires_at  timestamptz,          -- NULL = never expires
    version     bigint      NOT NULL DEFAULT 1 CHECK (version >= 1)
);

-- The race-proof idempotency guard: one allocation per logical request per
-- tenant. Concurrent duplicate creates lose here, not in application code.
CREATE UNIQUE INDEX allocations_tenant_request_uk
    ON allocations (tenant_id, request_id);

-- Serves both ListAllocations orderings: the unfiltered list is
-- (tenant_id, created_at DESC, id DESC) exactly, and the status-filtered
-- variant is satisfied by the partial scan of the same shape below.
CREATE INDEX allocations_tenant_created_idx
    ON allocations (tenant_id, created_at DESC, id DESC);

-- Status-filtered listing (tenant_id + status + keyset). Kept as one
-- composite rather than a bare (tenant_id, status): the sort columns make
-- the paginated scan index-only in order.
CREATE INDEX allocations_tenant_status_created_idx
    ON allocations (tenant_id, status, created_at DESC, id DESC);

-- Deliberately NOT indexed (no Phase 1 query pattern): tenant_id+resource_id
-- - add when a by-resource query lands, not before.

-- +goose Down
DROP TABLE allocations;
