import type { ChatbarState } from '../store/types.js';

/**
 * Single source of truth for the Chat Bar and Chat Card trigger designs.
 * The organism story (stories/organisms/cw-chatbar.stories.ts) and the
 * template story (stories/templates/cw-widget-root.stories.ts) both apply
 * these exact objects, so every preview renders identical design config.
 */
export const CHATBAR_BAR_PRESET: ChatbarState = {
  enabled: true,
  layout: 'bar',
  useWebsiteTheme: false,
  position: 'bottom-right',
  offsetLeft: 16,
  offsetRight: 16,
  offsetBottom: 12,
  cardOffsetRight: 16,
  cardOffsetBottom: 12,
  barOffsetRight: 16,
  barOffsetBottom: 12,
  text: 'Chat with us',
  cardText: 'Questions about PhonePe\nfor business?',
  barText: 'Chat with us',
  bgColor: '#000000',
  textColor: '#ffffff',
  textSize: 16,
  letterSpacing: 0,
  gradientEnabled: false,
  gradientStops: [
    { color: '#000000', pos: 0 },
    { color: '#000000', pos: 100 },
  ],
  gradientType: 'linear',
  gradientAngle: 90,
  iconType: 'lucide',
  iconColor: '#ffffff',
  lucideIcon: 'Chat',
  iconImageUrl: '',
  iconFit: 'contain',
  iconOpacity: 1,
  iconBlend: 'normal',
  iconWidth: 36,
  iconHeight: 36,
  width: 255,
  height: 40,
  shadow: true,
  borderRadius: { tl: 20, tr: 20, bl: 20, br: 20 },
  hideOnOpen: true,
  padding: '0 18px',
  gap: 0,
  buttonBg: '#ffffff',
  buttonTextColor: '#ffffff',
  buttonText: 'Chat Now',
};

/**
 * The Chat Card is the card-layout variant of the bar trigger with its own
 * sizing, radius, padding and button color pairing.
 */
export const CHATBAR_CARD_PRESET: ChatbarState = {
  enabled: true,
  layout: 'card',
  useWebsiteTheme: false,
  position: 'bottom-right',
  offsetLeft: 16,
  offsetRight: 16,
  offsetBottom: 12,
  cardOffsetRight: 200,
  cardOffsetBottom: 12,
  barOffsetRight: 16,
  barOffsetBottom: 12,
  text: 'Chat with us',
  barText: 'Chat with us',
  cardText: 'Questions about PhonePe for business?',
  bgColor: '#5f259f',
  textColor: '#ffffff',
  textSize: 16,
  letterSpacing: 0,
  gradientEnabled: false,
  gradientStops: [
    { color: '#5f259f', pos: 0 },
    { color: '#a855f7', pos: 100 },
  ],
  gradientType: 'linear',
  gradientAngle: 90,
  iconType: 'lucide',
  iconColor: '#ffffff',
  lucideIcon: 'MessageSquare',
  iconImageUrl: '',
  iconFit: 'contain',
  iconOpacity: 1,
  iconBlend: 'normal',
  iconWidth: 36,
  iconHeight: 36,
  width: 250,
  height: 220,
  shadow: true,
  borderRadius: 24,
  hideOnOpen: true,
  padding: '24px 20px',
  gap: 12,
  buttonBg: '#ffffff',
  buttonTextColor: '#5f259f',
  buttonText: 'Chat Now',
};
